// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArWLVP6ahsN0YO5fndBvF-QZbP8C4ENEU',
    appId: '1:1041820360029:web:4753ec1a53944cf0311cb4',
    messagingSenderId: '1041820360029',
    projectId: 'ridemate-43114',
    authDomain: 'ridemate-43114.firebaseapp.com',
    storageBucket: 'ridemate-43114.firebasestorage.app',
    measurementId: 'G-KPF5GZLEH1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMApuxgAFeKFRMV8a5hLKkkDJgGnfNLeY',
    appId: '1:1041820360029:android:1250302b083a6564311cb4',
    messagingSenderId: '1041820360029',
    projectId: 'ridemate-43114',
    storageBucket: 'ridemate-43114.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCldOt6QXHmjfk-Ux_ueiBPIZGifbMqJ_8',
    appId: '1:1041820360029:ios:b1b0954703407582311cb4',
    messagingSenderId: '1041820360029',
    projectId: 'ridemate-43114',
    storageBucket: 'ridemate-43114.firebasestorage.app',
    iosBundleId: 'com.abhishekverma.ridemate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCldOt6QXHmjfk-Ux_ueiBPIZGifbMqJ_8',
    appId: '1:1041820360029:ios:b1b0954703407582311cb4',
    messagingSenderId: '1041820360029',
    projectId: 'ridemate-43114',
    storageBucket: 'ridemate-43114.firebasestorage.app',
    iosBundleId: 'com.abhishekverma.ridemate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArWLVP6ahsN0YO5fndBvF-QZbP8C4ENEU',
    appId: '1:1041820360029:web:d2ded0548a48a4f9311cb4',
    messagingSenderId: '1041820360029',
    projectId: 'ridemate-43114',
    authDomain: 'ridemate-43114.firebaseapp.com',
    storageBucket: 'ridemate-43114.firebasestorage.app',
    measurementId: 'G-RR6D7CMVJK',
  );
}
